### ISSUE TITLE
xcode6 beta3里报错

### ISSUE THREAD

**Issue by l12ab** [zhaokaiyuan99/PullRefresh#2]
第87行，override func observeValueForKeyPath 这个函数。

另外，第40行也报错。if NSUserDefaults.standardUserDefaults().objectForKey(RefreshHeaderTimeKey) == nil  。
似乎和SwiftyJSON这个库冲突 https://github.com/lingoer/SwiftyJSON

**Comment by zhaokaiyuan99** [comment]
用XCODE 6 BETA1 写的 等周末下载XCODE 6 BETA3 在修复吧 现在没时间

**Comment by zhaokaiyuan99** [comment]
已解决

**Comment by zhaokaiyuan99** [comment]
另外 json 解析 可以用苹果自带库 速度快 安全
